name: üì¶ Expo EAS Local Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android-local:
    runs-on: ubuntu-latest

    steps:
      - name: üèó Setup repository
        uses: actions/checkout@v4

      - name: üß± Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üß∞ Setup EAS CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: üì¶ Install dependencies
        run: npm install

      - name: üß© Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: üîê Decode custom keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.jks

      - name: üèóÔ∏è Build Android AAB (production)
        run: eas build --platform android --profile production --local --non-interactive
        env:
          EAS_NO_VCS: 1
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          ANDROID_KEYSTORE_PATH: my-release-key.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: üèóÔ∏è Build Android APK (preview)
        run: eas build --platform android --profile preview --local --non-interactive
        env:
          EAS_NO_VCS: 1
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          ANDROID_KEYSTORE_PATH: my-release-key.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: üì§ Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: BatteryPlus-aab
          path: "**/*.aab"

      - name: üì§ Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BatteryPlus-apk
          path: "**/*.apk"
